spring:
  application:
    name: smart-pay
  profiles:
    active: active
  mvc:
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    basename: i18n/messages


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.pku.smart.modules.*.entity
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: not_null
  configuration:
    database-id: sqlserver
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: "count=countSql"

avatar:
  file:
    uploadpath: "c:/avatar/"

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

smart:
  # 实例演示开关
  demoEnabled: false
  # 文件路径 示例（ Windows配置D:/uploadPath，Linux配置 /home/uploadPath）
  profile: C:/avatar
  # 获取ip地址开关
  addressEnabled: true

jasypt:
  encryptor:
    password: xxx #加密中的 “盐（salt）” java -jar -Djasypt.encryptor.password=123456 xxx.jar
    algorithm: PBEWithMD5AndDES #配置要使用的加密算法，默认值是 PBEWithMD5AndDES
    string-output-type: base64
    pool-size: 1
    key-obtention-iterations: 1000
